### ISSUE TITLE
Location getter fails on incomplete location string

### ISSUE THREAD

**Issue by eawer** [boxing/boxrec#86]
Code:
```js
const boxrec = require("boxrec");

(async () => {
    await boxrec.login(login, password);
    const event = await boxrec.getEventById(775798);
    console.log(event._location);
    console.log(event.location);
}()
```

Output:
```
<div class="flag at"></div><a href="/en/locations/event?country=AT">Austria</a>

(node:7433) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'children' of undefined
    at t.get [as location] (node_modules/boxrec/dist/index.js:158:16751)
    at test.js:8:23
    at <anonymous>
```

Looks like the issue is that only country name is present. Possibly affects other getters, which assume that all nested data is always present

**Comment by mikedidomizio** [comment]
Yes, first time I've ran into just the country being listed.  The location parsing is a bit of a mess but I did a tiny bit of refactoring.  
Resolved this with this pull request https://github.com/boxing/boxrec/pull/87

Thanks for the detailed comment!

Upgrade to version **0.18.4**
